#!/usr/bin/env bash
# @fileoverview Idempotent installer for voice-dictate. Verifies dependencies,
# prompts for runtime config, writes the shell + Hammerspoon config files,
# symlinks the Lua module into ~/.hammerspoon, patches init.lua, reloads.
#
# Run from anywhere: `./install.sh` (uses BASH_SOURCE to resolve repo paths).
# Re-runs are safe — prompts pre-fill from the existing config when present.

set -euo pipefail

# ───── paths ────────────────────────────────────────────────────────────────

# Absolute path to this repo's root, derived from the script location.
readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source Lua module shipped by this repo (main entry).
readonly SRC_LUA="${REPO_ROOT}/hammerspoon/voice-dictate.lua"

# Sibling Lua module shipped alongside the main one (mic picker).
# Lua's require() resolves siblings via ~/.hammerspoon's package.path, so it
# must be symlinked next to voice-dictate.lua.
readonly SRC_LUA_MIC="${REPO_ROOT}/hammerspoon/voice-dictate-mic.lua"

# Destination symlink inside the user's Hammerspoon config directory.
readonly DST_LUA="${HOME}/.hammerspoon/voice-dictate.lua"

# Destination symlink for the mic-picker sibling module.
readonly DST_LUA_MIC="${HOME}/.hammerspoon/voice-dictate-mic.lua"

# User's Hammerspoon entry point — patched to require the voice-dictate module.
readonly INIT_LUA="${HOME}/.hammerspoon/init.lua"

# Single line appended to init.lua; checked verbatim to keep the patch idempotent.
readonly LOADER_LINE='require("voice-dictate").start()'

# Local config files written by this installer — both are required at runtime.
readonly SHELL_CONFIG="${REPO_ROOT}/bin/config.local.sh"
readonly LUA_CONFIG="${HOME}/.hammerspoon/voice-dictate-config.lua"

# Project defaults — used by the prompts when there is no prior config.
readonly DEFAULT_MODEL="${HOME}/whisper-models/ggml-large-v3-turbo-q5_0.bin"
readonly DEFAULT_LANGUAGE="el"

# ───── helpers ──────────────────────────────────────────────────────────────

# Abort with message on stderr if a required command is missing.
function require_cmd() {
  local cmd="${1}"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "install: missing required command: ${cmd}" >&2
    exit 1
  fi
}

# Verify every external dependency before mutating anything on disk.
function verify_deps() {
  require_cmd ffmpeg
  require_cmd whisper-cli
  if [[ ! -d "/Applications/Hammerspoon.app" ]]; then
    echo "install: Hammerspoon.app not found in /Applications" >&2
    exit 1
  fi
}

# Prompt the user with a default; print the chosen value to stdout.
# Uses bash read -p, which writes the prompt to stderr — safe inside $(…).
function ask() {
  local prompt="${1}"
  local default="${2}"
  local answer
  read -r -p "${prompt} [${default}]: " answer
  echo "${answer:-${default}}"
}

# Write bin/config.local.sh with the chosen MODEL_PATH and LANGUAGE plus
# the technical defaults that almost nobody needs to tune (THREADS, AUDIO_DEVICE).
function write_shell_config() {
  local model_path="${1}"
  local language="${2}"
  cat > "${SHELL_CONFIG}" <<EOF
# voice-dictate shell config — generated by install.sh; gitignored.
# Edit to change defaults. Per-invocation env overrides still work:
#   LANGUAGE=en ./bin/dictate.sh smoke

: "\${MODEL_PATH:=${model_path}}"
: "\${LANGUAGE:=${language}}"
: "\${THREADS:=8}"
: "\${AUDIO_DEVICE:=:0}"
EOF
  echo "install: wrote ${SHELL_CONFIG}"
}

# Write ~/.hammerspoon/voice-dictate-config.lua with the absolute path to
# dictate.sh plus the hotkey + flush-delay defaults. Loaded by the Lua module
# via require("voice-dictate-config") on every Hammerspoon reload.
function write_lua_config() {
  mkdir -p "${HOME}/.hammerspoon"
  cat > "${LUA_CONFIG}" <<EOF
-- voice-dictate Hammerspoon config — generated by install.sh.
-- Edit to change defaults, then run hs.reload() from the Hammerspoon Console.

return {
  dictate_sh = "${REPO_ROOT}/bin/dictate.sh",
  toggle_mods = {"cmd", "shift"},
  toggle_key = "D",
  right_alt_keycode = 61,
  flush_delay_s = 0.2,
}
EOF
  echo "install: wrote ${LUA_CONFIG}"
}

# Symlink the Lua modules into ~/.hammerspoon, overwriting any prior links.
# Both files must live in ~/.hammerspoon for Lua's require() to find the sibling.
function link_module() {
  mkdir -p "${HOME}/.hammerspoon"
  ln -sf "${SRC_LUA}" "${DST_LUA}"
  echo "install: linked ${DST_LUA} -> ${SRC_LUA}"
  ln -sf "${SRC_LUA_MIC}" "${DST_LUA_MIC}"
  echo "install: linked ${DST_LUA_MIC} -> ${SRC_LUA_MIC}"
}

# Append the loader line to init.lua if it isn't already present.
function patch_init_lua() {
  if [[ -f "${INIT_LUA}" ]] && grep -Fq "${LOADER_LINE}" "${INIT_LUA}"; then
    echo "install: init.lua already requires voice-dictate — skipping patch"
    return 0
  fi
  printf '\n-- voice-dictate (installed by voice-dictate/install.sh)\n%s\n' \
    "${LOADER_LINE}" >> "${INIT_LUA}"
  echo "install: patched ${INIT_LUA}"
}

# Trigger Hammerspoon to reload its config without restarting the app.
function reload_hammerspoon() {
  open -g "hammerspoon://reload"
  echo "install: requested Hammerspoon reload"
}

# Print a warning (not a fatal error) when the chosen model is not on disk.
function warn_if_missing_model() {
  local model_path="${1}"
  if [[ ! -f "${model_path}" ]]; then
    echo "install: warning — model file not found at ${model_path}." >&2
    echo "         download it before first use; see README.md § Model download." >&2
  fi
}

# ───── entry point ──────────────────────────────────────────────────────────

function main() {
  verify_deps

  # Determine config values. If a prior shell config exists, source it so
  # MODEL_PATH and LANGUAGE pre-fill the prompts with the user's saved values.
  local cur_model="${DEFAULT_MODEL}"
  local cur_language="${DEFAULT_LANGUAGE}"
  if [[ -f "${SHELL_CONFIG}" ]]; then
    # shellcheck source=/dev/null
    source "${SHELL_CONFIG}"
    cur_model="${MODEL_PATH:-${cur_model}}"
    cur_language="${LANGUAGE:-${cur_language}}"
  fi

  echo
  echo "voice-dictate config — press Enter to accept defaults."
  local cfg_model
  cfg_model="$(ask "Whisper model path" "${cur_model}")"
  local cfg_language
  cfg_language="$(ask "Default language (el, en, auto, …)" "${cur_language}")"

  warn_if_missing_model "${cfg_model}"

  write_shell_config "${cfg_model}" "${cfg_language}"
  write_lua_config
  link_module
  patch_init_lua
  reload_hammerspoon
  echo "install: done. Grant Accessibility + Microphone to Hammerspoon if prompted."
}

main "$@"
