#!/usr/bin/env bash
# @fileoverview Configuration file writers. Generates the shell-side runtime
# config (bin/config.local.sh) sourced by dictate.sh and the Lua-side hotkey
# config (~/.hammerspoon/voice-dictate-config.lua) loaded by the Hammerspoon
# module. Uses the : "${VAR:=…}" override pattern so pre-set env values still
# win over the persisted defaults.

set -euo pipefail

# Source lib.sh from the same directory so log() is available.
# shellcheck source=lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

# Write the shell-side runtime config file sourced by dictate.sh.
# Re-runs are safe — the file is overwritten in full each time.
# $1 — destination path for the generated config (typically bin/config.local.sh).
# $2 — MODEL_PATH default to embed in the file.
# $3 — LANGUAGE default to embed in the file.
function write_shell_config() {
  local destination="${1}"
  local model_path="${2}"
  local language="${3}"
  cat > "${destination}" <<EOF
# voice-dictate shell config — generated by install.sh; gitignored.
# Edit to change defaults. Per-invocation env overrides still work:
#   LANGUAGE=en ./bin/dictate.sh smoke

: "\${MODEL_PATH:=${model_path}}"
: "\${LANGUAGE:=${language}}"
: "\${THREADS:=8}"
: "\${AUDIO_DEVICE:=:0}"
EOF
  log ok "wrote ${destination}"
}

# Write the Lua-side config file loaded by the Hammerspoon module on every reload.
# The file lives outside the repo so user edits survive a clean re-clone.
# stream_sh and server_sh are derived from dictate_sh — they always live in
# the same bin/ dir.
# $1 — destination path (typically ~/.hammerspoon/voice-dictate-config.lua).
# $2 — absolute path to bin/dictate.sh that the Lua module will invoke.
function write_lua_config() {
  local destination="${1}"
  local dictate_sh="${2}"
  local bin_dir="${dictate_sh%/*}"
  mkdir -p "$(dirname "${destination}")"
  cat > "${destination}" <<EOF
-- voice-dictate Hammerspoon config — generated by install.sh.
-- Edit to change defaults, then run hs.reload() from the Hammerspoon Console.

return {
  dictate_sh = "${dictate_sh}",
  stream_sh = "${bin_dir}/stream.sh",
  server_sh = "${bin_dir}/stream-server.sh",
  toggle_mods = {"cmd", "shift"},
  toggle_key = "D",
  right_alt_keycode = 61,
  hide_hammerspoon_icon = true,
}
EOF
  log ok "wrote ${destination}"
}
