--- @fileoverview Hotkey-driven local dictation: PTT + toggle, ffmpeg + whisper-server backend.
---
--- Owns the macOS-side behaviour — hotkeys, lifecycle, menubar — and delegates
--- the streaming pipeline to voice-dictate-stream-mode.lua. Right Option (held)
--- and the toggle hotkey both drive a streaming session: text appears in the
--- focused field while the user keeps speaking, via the clipboard-mediated
--- splice. The single-shot record-then-transcribe path that this module used
--- to drive lives in bin/dictate.sh for ad-hoc shell use; no hotkey reaches
--- it any more (see engineering/plans/2026-05-28-streaming-replaces-single-shot.md).
---
--- Runtime config is loaded from ~/.hammerspoon/voice-dictate-config.lua, which
--- install.sh generates. Edit that file and hs.reload() to change settings.
---
--- Public API:
---   M.start()  bind hotkeys, mount the command center. Idempotent — calls stop() first.
---   M.stop()   tear down hotkeys + menubar + any in-flight session. Safe to repeat.

local M = {}

-- ───── local config ─────────────────────────────────────────────────────────

--- User-specific runtime config, generated by install.sh. Provides:
--- toggle_mods, toggle_key, right_alt_keycode, stream_sh, server_sh, and
--- the optional hide_hammerspoon_icon. dictate_sh is also present for
--- ad-hoc shell use but no hotkey reaches it.
local cfg = require("voice-dictate-config")

--- Modifier set for the toggle hotkey (tap to start, tap to stop).
local TOGGLE_MODS = cfg.toggle_mods

--- Key bound alongside TOGGLE_MODS to start/stop the streaming session.
local TOGGLE_KEY = cfg.toggle_key

--- macOS keycode for Right Option — the PTT trigger. Left Option (58) is ignored.
local RIGHT_ALT_KEYCODE = cfg.right_alt_keycode

--- Hide Hammerspoon's own menubar icon so the Dikta item is the one control
--- surface. Defaults true when the config key is absent; set
--- hide_hammerspoon_icon = false in the config to keep Hammerspoon's icon.
local HIDE_HS_ICON = cfg.hide_hammerspoon_icon ~= false

--- Menubar command center — icon, dropdown, streaming title.
--- See voice-dictate-menu.lua.
local menu = require("voice-dictate-menu")

--- Streaming-session orchestrator — composes the stdout consumer and the
--- splice paste layer. See voice-dictate-stream-mode.lua.
local streamMode = require("voice-dictate-stream-mode")

-- ───── module state ─────────────────────────────────────────────────────────

--- Binding handle for the toggle hotkey (returned by hs.hotkey.bind).
local hotkeyToggle = nil

--- Eventtap watching flagsChanged events to implement push-to-talk on Right Option.
local pttTap = nil

--- Eventtap watching keyDown events so any ordinary keystroke stops an active
--- session (see engineering/plans/2026-05-31-keypress-stop.md). Always-on while
--- mounted, like pttTap; its handler no-ops unless a session is running.
local keyStopTap = nil

-- ───── helpers ──────────────────────────────────────────────────────────────

--- Format the toggle hotkey as menu-friendly glyphs, e.g. "⌘⇧D".
--- @return string The modifier symbols followed by the toggle key.
local function hotkeyHint()
  local symbols = {cmd = "⌘", shift = "⇧", alt = "⌥", option = "⌥",
                   ctrl = "⌃", control = "⌃"}
  local hint = ""
  for _, modifier in ipairs(TOGGLE_MODS) do
    hint = hint .. (symbols[modifier] or "")
  end
  return hint .. TOGGLE_KEY
end

--- Play the macOS Tink sound (start cue). No-op if the system sound is missing.
local function playStartCue()
  local s = hs.sound.getByName("Tink")
  if s then s:play() end
end

--- Play the macOS Pop sound (stop cue). No-op if the system sound is missing.
local function playStopCue()
  local s = hs.sound.getByName("Pop")
  if s then s:play() end
end

-- ───── state transitions ────────────────────────────────────────────────────

--- Start a streaming session and signal the menubar + audio cue.
--- No-op if a session is already active.
local function startSession()
  if streamMode.isActive() then
    print("[vd-ptt] startSession: skip (already active)")
    return
  end
  print("[vd-ptt] startSession: begin")
  streamMode.startSession(cfg)
  menu.setState("streaming")
  playStartCue()
  print("[vd-ptt] startSession: end")
end

--- Stop the active streaming session. The menubar flips to "finalizing"
--- immediately so the user gets a visual signal that work continues past
--- PTT release (ffmpeg flush + whisper-server final pass + splice paste).
--- When streamMode's onDone fires — after the final transcript has pasted
--- — the menubar drops to idle. The Pop sound plays on release as the
--- session-ended cue; the spinner indicates "transcript still incoming".
--- No-op if nothing is running.
local function stopSession()
  if not streamMode.isActive() then
    print("[vd-ptt] stopSession: skip (not active)")
    return
  end
  print("[vd-ptt] stopSession: begin")
  menu.setState("finalizing")
  playStopCue()
  streamMode.stopSession(function()
    menu.setState("idle")
    print("[vd-ptt] stopSession: finalized")
  end)
  print("[vd-ptt] stopSession: end")
end

-- ───── input handlers ───────────────────────────────────────────────────────

--- Toggle handler: flip the streaming session on each tap of TOGGLE_MODS + TOGGLE_KEY.
local function onToggleTap()
  if streamMode.isActive() then stopSession() else startSession() end
end

--- PTT handler. Fires on every modifier change; filters to Right Option keycode
--- and uses the alt flag to distinguish press (start) from release (stop).
---
--- The actual start/stop work is deferred to a zero-delay timer so this
--- callback returns to the eventtap in microseconds. macOS auto-disables
--- event taps whose callback exceeds the OS-side timeout (~1s); the first
--- PTT press of a session pays a ~1s tax loading hs.pasteboard,
--- hs.window.filter, hs.timer, and hs.sound, which without deferral would
--- starve the very next flagsChanged event (the Right Option release)
--- and silently drop it. Deferring keeps the tap responsive.
--- @param event hs.eventtap.event The flagsChanged event.
--- @return boolean Always false — never swallow the event.
local function onFlagsChanged(event)
  if event:getKeyCode() ~= RIGHT_ALT_KEYCODE then return false end
  local flags = event:getFlags()
  if flags.alt and not streamMode.isActive() then
    hs.timer.doAfter(0, startSession)
  elseif not flags.alt and streamMode.isActive() then
    hs.timer.doAfter(0, stopSession)
  end
  return false
end

--- Keystroke handler. While a session is active, any ordinary key (one whose
--- flags carry no Cmd/Ctrl/Alt) stops it — the user has started typing, which
--- is the "I'll take it from here" gesture. The no-modifier filter is also what
--- keeps the splice layer's own synthetic Cmd+X / Cmd+V / Shift+Cmd+Up from
--- self-cancelling the session: every synthetic keystroke carries Cmd, as does
--- the toggle combo, so all of them are excluded by the same test. Stop is
--- deferred to a zero-delay timer (same rationale as onFlagsChanged) and the
--- event is never swallowed, so the triggering key lands in the field.
--- @param event hs.eventtap.event The keyDown event.
--- @return boolean Always false — never swallow the keystroke.
local function onKeyStop(event)
  if not streamMode.isActive() then return false end
  local flags = event:getFlags()
  if flags.cmd or flags.ctrl or flags.alt then return false end
  hs.timer.doAfter(0, stopSession)
  return false
end

-- ───── lifecycle ────────────────────────────────────────────────────────────

--- Bind global hotkeys and start the flagsChanged eventtap.
local function bindHotkeys()
  hotkeyToggle = hs.hotkey.bind(TOGGLE_MODS, TOGGLE_KEY, onToggleTap)
  pttTap = hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, onFlagsChanged)
  pttTap:start()
  keyStopTap = hs.eventtap.new({hs.eventtap.event.types.keyDown}, onKeyStop)
  keyStopTap:start()
end

--- Unbind global hotkeys and stop the flagsChanged + keyDown eventtaps.
local function unbindHotkeys()
  if hotkeyToggle then hotkeyToggle:delete(); hotkeyToggle = nil end
  if pttTap then pttTap:stop(); pttTap = nil end
  if keyStopTap then keyStopTap:stop(); keyStopTap = nil end
end

--- Mount the command center + bind hotkeys. Idempotent: tears down prior state.
--- The injected control table lets the menu module read session state and
--- invoke start/stop, the Hammerspoon Console, reload, and icon-restore without
--- a circular require back into this module.
function M.start()
  M.stop()
  streamMode.init()
  menu.mount({
    onToggle = onToggleTap,
    isStreaming = function() return streamMode.isActive() end,
    onOpenConsole = function() hs.openConsole() end,
    onReload = function() hs.reload() end,
    onShowHsIcon = function() hs.menuIcon(true) end,
    hotkeyHint = hotkeyHint(),
    hideHsIcon = HIDE_HS_ICON,
  })
  bindHotkeys()
  print("voice-dictate: ready (PTT = Right Option, Toggle = " ..
    table.concat(TOGGLE_MODS, "+") .. "+" .. TOGGLE_KEY .. ")")
end

--- Tear down hotkeys + command center + any in-flight session. Safe to repeat.
--- Does not restore Hammerspoon's menu icon (see menubar command-center plan D3).
function M.stop()
  unbindHotkeys()
  streamMode.stopSession()
  menu.unmount()
end

return M
