--- @fileoverview Hotkey-driven local dictation: PTT + toggle, whisper.cpp backend.
---
--- Spawns bin/dictate.sh for the actual recording and transcription; this module
--- owns the macOS-side behavior: hotkeys, state machine, paste. The menubar
--- command center (icon, dropdown, recording title, spinner) lives in
--- voice-dictate-menu.lua and is driven through an injected control table.
---
--- Runtime config is loaded from ~/.hammerspoon/voice-dictate-config.lua, which
--- install.sh generates. Edit that file and hs.reload() to change settings.
---
--- Public API:
---   M.start()  bind hotkeys, mount the command center. Idempotent — calls stop() first.
---   M.stop()   tear down hotkeys + menubar + any in-flight task. Safe to repeat.

local M = {}

-- ───── local config ─────────────────────────────────────────────────────────

--- User-specific runtime config, generated by install.sh. Provides: dictate_sh,
--- toggle_mods, toggle_key, right_alt_keycode, flush_delay_s, and the optional
--- hide_hammerspoon_icon.
local cfg = require("voice-dictate-config")

--- Absolute path to the shell entry point that records and transcribes audio.
local DICTATE_SH = cfg.dictate_sh

--- Modifier set for the toggle hotkey (tap to start, tap to stop).
local TOGGLE_MODS = cfg.toggle_mods

--- Key bound alongside TOGGLE_MODS to start/stop dictation.
local TOGGLE_KEY = cfg.toggle_key

--- macOS keycode for Right Option — the PTT trigger. Left Option (58) is ignored.
local RIGHT_ALT_KEYCODE = cfg.right_alt_keycode

--- Seconds to wait after stopping recording before reading the WAV — gives
--- ffmpeg time to flush the trailer cleanly on SIGTERM.
local FLUSH_DELAY_S = cfg.flush_delay_s

--- Hide Hammerspoon's own menubar icon so the Dikta item is the one control
--- surface. Defaults true when the config key is absent; set
--- hide_hammerspoon_icon = false in the config to keep Hammerspoon's icon.
local HIDE_HS_ICON = cfg.hide_hammerspoon_icon ~= false

--- Mic picker — scan / persist / menu. See voice-dictate-mic.lua.
local mic = require("voice-dictate-mic")

--- Menubar command center — icon, dropdown, recording title, spinner.
--- See voice-dictate-menu.lua.
local menu = require("voice-dictate-menu")

--- Opt-in streaming-mode orchestrator — owns its own hotkey + state, does
--- not share runtime state with the single-shot path. See
--- voice-dictate-stream-mode.lua.
local streamMode = require("voice-dictate-stream-mode")

-- ───── module state ─────────────────────────────────────────────────────────

--- True between startRecording() and stopRecording().
local recording = false

--- The hs.task running ffmpeg. Nil when idle. Terminated via task:terminate().
local recordTask = nil

--- Absolute path of the WAV being captured for the current utterance.
local currentWav = nil

--- Binding handle for the toggle hotkey (returned by hs.hotkey.bind).
local hotkeyToggle = nil

--- Eventtap watching flagsChanged events to implement push-to-talk on Right Option.
local pttTap = nil

-- ───── helpers ──────────────────────────────────────────────────────────────

--- Compute a unique temporary WAV path under /tmp.
--- @return string Absolute /tmp path with a unix-timestamp suffix.
local function newWavPath()
  return string.format("/tmp/voice-dictate-%d.wav", os.time())
end

--- Format the toggle hotkey as menu-friendly glyphs, e.g. "⌘⇧D".
--- @return string The modifier symbols followed by the toggle key.
local function hotkeyHint()
  local symbols = {cmd = "⌘", shift = "⇧", alt = "⌥", option = "⌥",
                   ctrl = "⌃", control = "⌃"}
  local hint = ""
  for _, modifier in ipairs(TOGGLE_MODS) do
    hint = hint .. (symbols[modifier] or "")
  end
  return hint .. TOGGLE_KEY
end

--- Play the macOS Tink sound (start cue). No-op if the system sound is missing.
local function playStartCue()
  local s = hs.sound.getByName("Tink")
  if s then s:play() end
end

--- Play the macOS Pop sound (stop cue). No-op if the system sound is missing.
local function playStopCue()
  local s = hs.sound.getByName("Pop")
  if s then s:play() end
end

--- Show a Hammerspoon notification — used for transcription failures.
--- @param title string Short header text.
--- @param body string Body text shown beneath the title.
local function notify(title, body)
  hs.notify.new({title = title, informativeText = body}):send()
end

--- Strip ANSI/VT100 escape sequences from a string. Defends against shell
--- init noise (e.g. bash-completion errors), whisper-cli color resets, and
--- anything else that injects byte 0x1B + sequence. Covers CSI (\e[…),
--- charset designation (\e(…, \e)…), OSC (\e]…BEL), and 2-byte ESC <letter>.
local function stripAnsi(s)
  return (s
    :gsub("\27%[[%d;?]*[a-zA-Z]", "")        -- CSI: ESC [ params letter
    :gsub("\27%]%d+;[^\7\27]*\7", "")        -- OSC: ESC ] params BEL
    :gsub("\27[%(%)%*%+][A-Za-z0-9]", "")    -- charset designation
    :gsub("\27[A-Za-z=>]", "")               -- 2-byte ESC <letter>
  )
end

--- Asynchronously transcribe the given WAV and paste the result. Uses hs.task
--- (NOT hs.execute) so the Hammerspoon main thread stays free to animate the
--- menubar spinner and respond to other input while whisper-cli runs.
---
--- hs.task spawns dictate.sh directly without going through a shell, so the
--- login-shell ANSI leak that affected hs.execute(cmd, true) cannot happen
--- here. dictate.sh's own perl ANSI-strip + the stripAnsi() pass keep the
--- transcript clean either way.
--- @param wav string Absolute path to the WAV to transcribe.
local function transcribeAndPaste(wav)
  if not wav then return end
  menu.startSpinner()
  local task = hs.task.new(DICTATE_SH,
    function(exitCode, stdOut, stdErr)
      menu.stopSpinner()
      if exitCode ~= 0 or stdOut == nil or stdOut:gsub("%s+", "") == "" then
        notify("voice-dictate", "transcription failed — see Hammerspoon Console")
        print(string.format("voice-dictate transcribe failed: exit=%s stderr=%q",
          tostring(exitCode), tostring(stdErr)))
        return
      end
      local transcript = stripAnsi(stdOut):gsub("^[\n%s]+", ""):gsub("[\n%s]+$", "")
      if transcript:find("\27") then
        print(string.format("[vd] WARNING: ESC byte survived stripAnsi — raw=%q clean=%q",
          stdOut:sub(1, 60), transcript:sub(1, 60)))
      end
      hs.pasteboard.setContents(transcript)
      hs.eventtap.keyStroke({"cmd"}, "v", 0)
    end,
    {"transcribe", wav})
  task:start()
end

-- ───── state transitions ────────────────────────────────────────────────────

--- Spawn dictate.sh record as a background task; transition to recording state.
--- The chosen mic is passed as a positional argument so Hammerspoon stays the
--- direct parent of dictate.sh / ffmpeg — wrapping in `/usr/bin/env` breaks
--- macOS TCC because `env` becomes the responsible process for mic access.
--- No-op if already recording (PTT held while toggle active, or vice versa).
local function startRecording()
  if recording then return end
  currentWav = newWavPath()
  local wav = currentWav
  recordTask = hs.task.new(DICTATE_SH,
    function(exitCode, _stdOut, stdErr)
      -- ffmpeg has actually exited (via SIGINT forwarded by dictate.sh's bash
      -- wrapper) and the WAV trailer is written. Transcribe NOW — driven by
      -- the task's own exit, not a timer.
      if exitCode ~= 0 then
        print(string.format("[vd] ffmpeg exit=%s stderr=%q", tostring(exitCode), tostring(stdErr)))
      end
      transcribeAndPaste(wav)
    end,
    {"record", currentWav, mic.loadAudioDevice()})
  recordTask:start()
  recording = true
  menu.setRecording(true)
  playStartCue()
end

--- Send ONE SIGTERM to ffmpeg and reset state. Transcription fires from the
--- recordTask exit callback (see startRecording) once ffmpeg has actually
--- finished and the WAV trailer is written — not on a fixed timer.
---
--- Why one SIGTERM, not three: ffmpeg treats 3+ signals received in rapid
--- succession as "Received > 3 system signals, hard exiting" — it aborts
--- without flushing the muxer, producing a zero-byte WAV. Sending exactly
--- one SIGTERM and waiting for the natural exit gives a complete WAV.
---
--- Why `hs.task.new("/bin/kill", ...)` rather than `recordTask:terminate()`:
--- the latter would signal Hammerspoon's direct child (the bash wrapper)
--- which then re-signals ffmpeg; an explicit kill by PID hits ffmpeg's
--- parent bash directly via the same path and keeps signal-source
--- bookkeeping in one place.
local function stopRecording()
  if not recording then return end
  if recordTask then
    local pid = recordTask:pid()
    -- Signal dictate.sh's bash wrapper. Bash traps SIGTERM and forwards SIGINT
    -- to ffmpeg, which flushes the WAV trailer and exits gracefully. The
    -- recordTask exit callback fires when bash exits, which triggers transcribe.
    -- Tested end-to-end by bin/test-record-shutdown.sh — typical shutdown
    -- latency is ~10ms.
    if pid and pid > 0 then
      hs.task.new("/bin/kill", nil, {"-TERM", tostring(pid)}):start()
    end
    recordTask = nil
  end
  recording = false
  menu.setRecording(false)
  playStopCue()
end

-- ───── input handlers ───────────────────────────────────────────────────────

--- Toggle handler: flip recording state on each tap of TOGGLE_MODS + TOGGLE_KEY.
local function onToggleTap()
  if recording then stopRecording() else startRecording() end
end

--- PTT handler. Fires on every modifier change; filters to Right Option keycode
--- and uses the alt flag to distinguish press (start) from release (stop).
--- @param event hs.eventtap.event The flagsChanged event.
--- @return boolean Always false — never swallow the event.
local function onFlagsChanged(event)
  if event:getKeyCode() ~= RIGHT_ALT_KEYCODE then return false end
  local flags = event:getFlags()
  if flags.alt and not recording then
    startRecording()
  elseif not flags.alt and recording then
    stopRecording()
  end
  return false
end

-- ───── lifecycle ────────────────────────────────────────────────────────────

--- Bind global hotkeys and start the flagsChanged eventtap.
local function bindHotkeys()
  hotkeyToggle = hs.hotkey.bind(TOGGLE_MODS, TOGGLE_KEY, onToggleTap)
  pttTap = hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, onFlagsChanged)
  pttTap:start()
end

--- Unbind global hotkeys and stop the flagsChanged eventtap.
local function unbindHotkeys()
  if hotkeyToggle then hotkeyToggle:delete(); hotkeyToggle = nil end
  if pttTap then pttTap:stop(); pttTap = nil end
end

--- Mount the command center + bind hotkeys. Idempotent: tears down prior state.
--- The injected control table lets the menu module read recording state and
--- invoke start/stop, the Hammerspoon Console, reload, and icon-restore without
--- a circular require back into this module.
function M.start()
  M.stop()
  menu.mount({
    onToggle = onToggleTap,
    isRecording = function() return recording end,
    onOpenConsole = function() hs.openConsole() end,
    onReload = function() hs.reload() end,
    onShowHsIcon = function() hs.menuIcon(true) end,
    hotkeyHint = hotkeyHint(),
    hideHsIcon = HIDE_HS_ICON,
  })
  bindHotkeys()
  streamMode.start(cfg)
  print("voice-dictate: ready (PTT = Right Option, Toggle = " ..
    table.concat(TOGGLE_MODS, "+") .. "+" .. TOGGLE_KEY ..
    ", Stream = " .. table.concat(cfg.stream_toggle_mods or {"cmd","shift"}, "+") ..
    "+" .. (cfg.stream_toggle_key or "S") .. ")")
end

--- Tear down hotkeys + command center + any in-flight recording. Safe to repeat.
--- Does not restore Hammerspoon's menu icon (see menubar command-center plan D3).
function M.stop()
  unbindHotkeys()
  streamMode.stop()
  menu.unmount()
  if recordTask then recordTask:terminate(); recordTask = nil end
  recording = false
end

return M
